### PR TITLE
higher resolution profile picture

### PR DESCRIPTION
**Pull request by rudibravo**
Put together a quick presentation on staging with the new logo
https://apps-stage-0.risevision.com/editor/workspace/aee0cb1a-02ff-4532-8c7a-36bc6e8600e5/?cid=07807743-300c-4095-8613-a975ecc8c1cb

### CODE REVIEW

**Comment by jungeunyoon** [comment]
@rudibravo Looks good. Wondering if it would optimize loadtime to limit size to specific dimensions but let's go with it and make adjustments if needed later? 👍

**Comment by sheadarlison** [comment]
Looks great @rudibravo

**Comment by rudibravo** [comment]
@jungeunyoon that's a good point, but I will defer it to @sheadarlison since using the original image resolution was part of the requirement.

On my opinion the 2 MB limits from twitter should be enough, but we can always revisit.

**Comment by sheadarlison** [comment]
@rudibravo @jungeunyoon Let's go with this and see how it is. Thanks

**Pull request merged**
